variable "project_id" {}
variable "region" {}
variable "zone" {}
variable "backend_bucket" {}
variable "state_name" {}
variable "network_name" {}
variable "subnet_name" {}
variable "workerpool_name" {}
variable "no_external_ip" {}
variable "cb_trigger_name" {}
variable "cb_filename" {}
variable "cb_repo_name" {}
variable "cb_repo_type" {}
variable "wp_disk_size" {}
